### ISSUE TITLE
latex-preamble-styles

### ISSUE THREAD

**Issue by kentemorrison** [OpenDiscreteMath/ibl-combinatorics#95]
Is this a new file? When I use it to process index.tex I get a lot of errors. If I don't use it, then I get an error saying that it is missing.

**Comment by oscarlevin** [comment]
Yes, I added that a few pull requests back to change the fonts and style the page headers.  I suspect the errors you get have to do with the fonts not being installed on your computer.  Perhaps comment out the first block of code and see if that fixes things.  Or comment out the entire file.

**Comment by mitchkeller** [comment]
Can you put the errors you're getting here on the issue, Kent? I just pulled and the LaTeX compiled without errors for me.

**Comment by kentemorrison** [comment]
Some font warnings but the LaTeX errors are almost solely "Command \nobreakspace unavailable in encoding T1."  Definitely font problems. Below is a little of the console output.


LaTeX Font Warning: Font shape `EU1/zpltlf/m/n' undefined
(Font)              using `EU1/lmr/m/n' instead on input line 371.

(/usr/local/texlive/2015/texmf-dist/tex/latex/amsfonts/umsa.fd)
(/usr/local/texlive/2015/texmf-dist/tex/latex/amsfonts/umsb.fd)
(/usr/local/texlive/2015/texmf-dist/tex/latex/stmaryrd/Ustmry.fd)

LaTeX Font Warning: Font shape `U/stmry/m/n' in size <5.5> not available
(Font)              size <5> substituted on input line 371.

(/usr/local/texlive/2015/texmf-dist/tex/latex/newpx/unpxmia.fd)
(/usr/local/texlive/2015/texmf-dist/tex/latex/newpx/unpxsym.fd)
(/usr/local/texlive/2015/texmf-dist/tex/latex/newpx/unpxsyc.fd)

LaTeX Font Warning: Font shape `OMS/cmsy/b/n' in size <5.5> not available
(Font)              size <5> substituted on input line 371.


LaTeX Font Warning: Font shape `OT1/cmr/m/n' in size <5.5> not available
(Font)              size <5> substituted on input line 371.

[5]
Underfull \hbox (badness 10000) in paragraph at lines 380--385


! LaTeX Error: Command \nobreakspace unavailable in encoding T1.

See the LaTeX manual or LaTeX Companion for explanation.
Type  H <return>  for immediate help.
 ...                                              
                                                  
l.393 \par
          
? s
OK, entering \scrollmode...

! LaTeX Error: Command \nobreakspace unavailable in encoding T1.

See the LaTeX manual or LaTeX Companion for explanation.
Type  H <return>  for immediate help.
 ...

**Comment by kentemorrison** [comment]
I did some sleuthing and found an explanation about \nobreakspace, which recommended adding this line, which I added to my latex-preamble-styles:

\DeclareTextCommand{\nobreakspace}{T1}{\leavevmode\nobreak\ }

The tilde character is the non-breaking space, and the ptx has lots of them.

**Comment by mitchkeller** [comment]
I see you're on TeXLive 2015. Can you try upgrading to 2017? I found some font issues that I was having with 2015 were resolved when I upgraded to 2017 recently when helping Alex and Matt with some formatting for Active Calculus. We definitely want to get to a point where this can build without too many weird hacks going on.

**Comment by oscarlevin** [comment]
I think that must be the issue.  I've noticed that when I try to run xelatex using Ubuntu's texlive distribution I get loads of errors, but none when I use the most recent TeXLive distribution installed on windows or linux.  

This probably means we should abandon the latex-preamble-styles file for the official release, and then we can always use it when building a copy for print or pdf.

**Comment by oscarlevin** [comment]
In my ubuntu setup (windows subsystem linux) I still can't compile.  I get warnings about spanish.  Is there any reason PTX set \setotherlanguage{spanish} and \setotherlanguage{vietnamese}?  

I don't mind having to compile with the newest texlive, but for general distribution, we should make this thing compile nicely.

**Comment by mitchkeller** [comment]
The language thing has been a problem for a while. I usually get a gripe about Vietnamese, but it just flies by without any impact. That's going to be a question for Rob, I'm afraid.

**Comment by mitchkeller** [comment]
Closing this since none of us seem to have had problems with this recently.
